config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/404', :to => 'application#not_found'
  get '/422', :to => 'application#unacceptable'
  get '/500', :to => 'application#internal_error'

  get '/auth/google_oauth2/callback', to: 'sessions#create'

  root 'application#welcome', :as => 'welcome'
  # get '/wildcraft_forager' => 'application#enter', :as => 'enter'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/dashboard' => 'users#index', :as => 'main'

  get '/about' => 'application#about', :as => 'about'
  get '/resources' => 'application#reading', :as => 'reading'



  get '/dashboard/categories' => 'categories#index', :as => 'categories'
  get '/categories/:id' => 'categories#show', :as => 'categories_teams'


  delete '/logout' => 'sessions#destroy', :as => 'logout'

  get '/dashboard/profile/:id/edit' => 'users#edit', :as => 'edit_profile'
  get '/dashboard/profile/:id' => 'users#show', :as => 'profile'

  resources :users, path: :profile, shallow: true, only: %i[show edit update]


  get '/members/:id' => 'users#show_member', :as => 'show_member'



  resources :topics do
    resources :posts
  end

  resources :posts do
    resources :comments
  end


  get '/topics/:id/members' => 'users#member_new', :as => 'new_topic_member'
  post '/topics/:id/members/:id' => 'users#member_create'

  get '/members/:id/profile' => 'users#member_show', :as => 'member_profile'


  get '/topics/:id/members' => 'topics#new_member', :as => 'new_member'
  post '/topics/:id/members' => 'topics#create'

end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :category, optional: true

  belongs_to :user, optional: true

  has_many :memberships
  has_many :users, through: :memberships

  has_many :posts

  include ActiveModel::Validations

  validates :name, presence: true
  validates :name, uniqueness: true

  scope :by_recent_update, -> { order(updated_at: :desc) }
  scope :alphabetical_order, -> {order(name: :asc)}

  scope :inactive, -> { where(status: true) }
  scope :active, -> { where(status: false) }

  # validates :location_id, presence: true


  # scope :active, -> { where(status: true) }
  # scope :pending, -> { where(status: false) }
  # def self.is_authorized(user_id)
  #    @topic.memberships.where(user_id: current_user.id, admin: true)
  # end

  def self.find_location(location_id)
    @location = Location.find_by_id(@topic.location_id).id
    return Location.where(id: @location).select(:id, :name).take
  end


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include ApplicationHelper
  before_action :require_logged_in
  before_action :authenticate_user, only: %i[update destroy new_member]

  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @user = current_user
    @topic = Topic.find_by_id(params[:user_id])
    @current_topics = current_user.memberships

    @topics = Topic.all
    @categories = Category.all
  end

  def new
    @topic = Topic.new
    @categories = Category.all
  end

  def new_member
    @topic = Topic.find_by_id(params[:id])
    @users = User.active
  end

  def create
    @topic = Topic.new(topic_params)
    current_user.memberships.create(topic: @topic, admin: true)
    if @topic.save
      current_user.memberships.build(topic: @topic, admin: true)
      flash[:success] = "Admin: topic created successfully!"
      # render 'topics/show', :layout => false
      redirect_to @topic
    else
      render :new
    end
  end


  def show
    @topic = Topic.find_by_id(params[:id])
    @admin_by_name = admin_by_name.capitalize

    @posts = @topic.posts
    @post = Post.new #@topic.posts.build

    @current_posts = @topic.posts

    @category_by_name = category_by_name if !!@topic.category_id
    @current_members = current_members

    @admin_invite = @current_members.empty? && is_admin?

    # if !!@current_posts
    #   @filters = [["Active", "active"], ["Inactive", "inactive"], ["Recent Update","by_recent_update", {:selected => "selected"}]]
    #
    #   if params[:sort]
    #     # @tasks = Task.send(params[:sort][:filters])
    #     @current_posts = @current_posts.send(params[:sort][:filters].parameterize.to_sym)
    #   # @topic.tasks = Task.all(:order => 'updated_at DESC')
    #   else
    #     @current_posts = @topic.posts.order(updated_at: :desc)
    #   end
    # end
    # render json: @topic

    # respond_to do |format|
    #   format.html {render 'index.html', :layout => false}
    #   format.js {render 'index.js', :layout => false}
    # end

  end


  def edit
    unless is_admin? == true
      redirect_to @topic
    end
    # @topic.memberships.where(user_id: current_user.id, admin: true)
  end


  def update
    @topic = Topic.find_by_id(params[:id])

# //new membership feature //
    if !topic_member_params.blank?
      @member = User.find_by_id(topic_member_params[:id])
      if @member != current_user
        @member.memberships.new(topic: @topic, admin: false)
        @member.save
      # current_user.memberships.build(topic: @topic, admin: true)
        flash[:success] = "Admin: new member added to topic!"
        redirect_to @topic
      else
        render :new_member
      end
# /END /new membership feature //

    elsif !topic_params.blank?
      @topic.update(topic_params)
        redirect_to  @topic
        flash[:update] = "Topic succesfully updated!"
    else
      render :edit
    end
  end


  def destroy
    @topic = Topic.find_by_id(params[:id])
    # if @topic.user_id == current_user.id
      @topic.delete
    # end
    flash[:deleted] = "Topic deleted."
    redirect_to dashboard_path
  end

  private

  def set_topic
    @topic = Topic.find_by_id(params[:id])
  end


  def topic_params
    params.require(:topic).permit(:name, :description, :category_id)
  end

  def authenticate_user
    if logged_in?
      unless is_admin?
        flash[:error] = "Sorry, admin access only."
      end
    end
  end

  # //new add_membership feature //
  def topic_member_params
    params.require(:topic).permit(:id)
  end

  def current_members
    @topic = Topic.find_by_id(params[:id])
    @current_members = Membership.where(topic_id: @topic, admin: false)
  end

  def member_by_name
    user  = @current_members.where( admin: false).pluck(:user_id)
    @member_by_name = User.find_by(id: user).name
  end
  #  // END //new add_membership feature //

  def is_admin?
    @topic = Topic.find_by_id(params[:id])
    user = Membership.where(user_id: current_user.id, admin: true).distinct.pluck(:user_id)
    @current_admin = user.join.to_i == current_user.id
    # @current_admin == @topic.memberships.map(&:user_id)
  end

  # def find_user_name(member)
  #   user = User.find_by_id(member.user_id)
  #   @find_user_name = user.name.capitalize
  # end

  # <%= link_to "#{find_user_name(member)}", show_member_path(member.user_id) %>
  #
  def admin_by_name
    admin_user = @topic.memberships.where(admin: true).pluck(:user_id)
    @admin_by_name = User.find_by(id: admin_user).name
  end

  # @topic = Topic.find_by_id(params[:id])
  # @admin = Membership.where(topic_id: @topic, user_id: current_user.id, admin: true).pluck(:user_id)


  def category_by_name
    category = Category.find_by_id(@topic.category_id)
    @category_by_name = category.name
  end

end

app/views/topics/_form.html.erb
<%= simple_form_for @topic do |f| %>

  <%= f.error_notification %>

  <br><br>

  <%= f.input :name, include_blank: false %><br><br>

  <%= f.input :description, include_blank: false %><br><br>

  <%= f.collection_select :category_id, Category.all.order(:name), :id, :name, {include_blank: "Select from existing categories"} %>

  <br><br>

  <div style="text-align: center;">
    <%= f.submit 'Create', class: "btn btn-lg btn-primary" %>
  </div>
  
<% end %>

app/views/topics/_index.html.erb
<div>
  <div style="text-align: center;">
    <div style="display: inline-block; text-align: left;">

      <h2>Current topics: <%= current_user.topics.length %></h2>

      <% current_user.topics.each do |topic| %>
        <li>
        <%= link_to "#{topic.name.capitalize}", topic_path(topic.id) %>
        </li>
      <% end %>

    </div>
  </div>
</div>

app/views/topics/edit.html.erb
<div>
  <div style="text-align: center;">
    <div style="display: inline-block; text-align: left;">

      <% if !!current_user %>
        <% if @topic.posts.empty? %>
          <h1 align="center">Project Status: pending</h1>

          <h3 align="center"><%= link_to "Add a post", new_topic_post_path(@topic) %> to change status to active. </h3>

        <% else %>
          <h1 align="center">Project Status: active</h1>
          <h3 align="center"><%= link_to "Add new post", new_topic_post_path(@topic) %></h3>
        <% end %>

        <h3 align="center"><%= link_to "Invite new member",  new_member_path(@topic) %></h3>
      <% end %>


      <h1>Edit your topic: <%= @topic.name %></h1>

      <%= simple_form_for @topic do |f| %>

        <%= f.error_notification %>

        <h3>General topic info:</h3>

        <%= f.input :name, include_blank: false %><br>

        <%= f.input :description, include_blank: false %><br>

        <%= f.collection_select :category_id, Category.all.order(:name), :id, :name, {include_blank: "Select frome existing categories"} %>

        <br><br>

        <%= f.submit 'Update', class: "btn btn-lg btn-primary" %>

      <% end %>

      <br><br>

      <%= button_to "Delete Topic", { :action => "destroy" }, class: "btn btn-lg btn btn-danger", :method => :delete, data: { confirm: "Are you sure?" } %>

    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div>
  <div style="text-align: center;">
    <div style="display: inline-block; text-align: left;">

      <h2>Current topics: <%= current_user.topics.length %></h2>

      <% current_user.topics.each do |topic| %>
        <li>
        <%= link_to "#{topic.name.capitalize}", topic_path(topic.id) %>
        </li>
      <% end %>




    <br>

    <div style="width: 500px;margin:auto">
      <img style="width: 500px" src="https://images.pexels.com/photos/1266005/pexels-photo-1266005.jpeg?auto=compress&cs=tinysrgb&h=650&w=940">
    </div>

    </div>
  </div>
</div>

app/views/topics/index.js.erb
// alert("Hello from Rails!")

//rails processed this first, the javascript sent back was dynamically generated by rails

var html = "<%= j(render('topics/index'))%>"

$("div.topics").html(html)

app/views/topics/new.html.erb
<div>
  <div style="text-align: center;">
    <div style="display: inline-block; text-align: left;">
      <h1 align="center">New Topic:</h1>
      <%= render 'form' %>
      </div>
  </div>
</div>

app/views/topics/new.js.erb
// alert("Hello from Rails!")

//rails processed this first, the javascript sent back was dynamically generated by rails

var html = "<%= j(render('topics/form'))%>"

$("div.new_topics").html(html)

app/views/topics/new_member.html.erb
<div>
  <div style="text-align: center;">
    <div style="display: inline-block; text-align: left;">

      <h1>Project: <%= link_to "#{@project.name}",  @project %></h1>

      <h2>Invite a member</h2>

      <%= simple_form_for @project do |f| %>

        <%= f.error_notification %>

        <br>

        <%= f.collection_select :id, @users, :id, :name, {include_blank: "Select member name"} %>

        <br><br>

        <%= f.submit 'Invite member!' %>

        <br><br>

      <% end %>

      <div style="width: 500px;margin:auto">
        <img style="width: 500px" src="https://images.pexels.com/photos/316465/pexels-photo-316465.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260">
      </div>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div>
  <div style="text-align: center;">
    <div style="display: inline-block; text-align: left;">

      <h3 align="center">Topic: <%= link_to "#{@topic.name}",  edit_topic_path(@topic) %></h3>
      <h3 align="center">Description: <%= @topic.description %></h3>
      <p>Category: <%= @category_by_name %></p>
      <p>Admin: <%= @admin_by_name %></p>

      <br><br>

      <li><%= link_to "New posts", new_topic_path, :class=> "new_topic", :remote => true %></li>
      <div class = "new_posts">
        <ul>

        </ul>
      </div>

      <%= simple_form_for [@topic, @post] do |f| %>
        <%= f.input :name %><br>
        <%= f.input :description %><br>
        <%= submit_tag "New Post" %>
      <% end %>

      <br><br>

      <% if !@current_posts.empty?%>
        <li><%= link_to "Load posts", topic_posts_path(@topic), :class=> "posts", :remote => true %></li>
        <br><br>

        <div class = "posts">
          <ul>

          </ul>
        </div>

      <% end %>
    </div>
  </div>
</div>