config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/404', :to => 'application#not_found'
  get '/422', :to => 'application#unacceptable'
  get '/500', :to => 'application#internal_error'

  get '/auth/google_oauth2/callback', to: 'sessions#create'

  root 'application#welcome', :as => 'welcome'
  # get '/wildcraft_forager' => 'application#enter', :as => 'enter'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/dashboard' => 'users#index', :as => 'main'

  get '/about' => 'application#about', :as => 'about'
  get '/resources' => 'application#reading', :as => 'reading'



  get '/dashboard/categories' => 'categories#index', :as => 'categories'
  get '/categories/:id' => 'categories#show', :as => 'categories_teams'


  delete '/logout' => 'sessions#destroy', :as => 'logout'

  get '/dashboard/profile/:id/edit' => 'users#edit', :as => 'edit_profile'
  get '/dashboard/profile/:id' => 'users#show', :as => 'profile'

  resources :users, path: :profile, shallow: true, only: %i[show edit update]


  get '/members/:id' => 'users#show_member', :as => 'show_member'



  resources :topics do
    resources :posts
  end

  resources :posts do
    resources :comments
  end


  get '/topics/:id/members' => 'users#member_new', :as => 'new_topic_member'
  post '/topics/:id/members/:id' => 'users#member_create'

  get '/members/:id/profile' => 'users#member_show', :as => 'member_profile'


  get '/topics/:id/members' => 'topics#new_member', :as => 'new_member'
  post '/topics/:id/members' => 'topics#create'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :memberships
  has_many :topics, through: :memberships

  has_many :posts

  # has_many :comments
  # has_many :posts, through: :comments


  include ActiveModel::Validations

  validates :name, presence: true

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  validates_length_of :name, within: 2..30, too_long: 'pick a shorter name', too_short: 'pick a longer name'

  scope :inactive, -> { where(status: false) }

  scope :active, -> { where(status: true) }

  def self.grab_teammate(user_id)
    @member = User.find_by_id(user_id).id
    return User.where(id: @member).select(:id, :name, :email, :time_zone, :language, :gender, :interest, :image).take
  end

  def self.find_user_name(user_id)
    user = User.find_by_id(user_id)
    @find_user_name = user.name
  end

end
  # before_validation :remove_whitespaces


  # private
  #
  # def remove_whitespaces
  #   name.strip!
  # end





  # validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/


  # validates_presence_of :slug
  #
  # def to_param
  # slug
  # end

  # extend FriendlyId
  # friendly_id :username, use: :slugged
  # validates :username, presence: true
  # validates :username, :uniqueness => {:case_sensitive => false},
  # :format => { with: /\A[a-zA-Z0-9]+\Z/ }



  #
  # def slug=(value)
  #   if value.present?
  #     write_attribute(:slug, value)
  #   end
  # end
  #
  # def should_generate_new_friendly_id?
  #   new_record? || slug.nil? || slug.blank? # you can add more condition here
  # end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, except: %i[new create]

  def index
    @user = current_user
    # @members = Member.search((user_params))

    @topics = Post.all
    @current_topics = @current_user.topics
  end


  def new
    if !current_user
      @user = User.new
    else
      redirect_to user_path(current_user)
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "User account created successfully!"
      redirect_to main_path
    else
      flash[:failure] = "Failure, user account not saved."
      render :new
    end
  end

  def show
    if params[:id].to_i == current_user.id
      render :show
    else
      redirect_to '/404'
    end
  end

# //new membership feature //
  def show_member
    if !!params[:id]
      @member = User.grab_teammate(params[:id])
      render show_member
    else
      redirect_to '/404'
    end
  end

  def edit
    @user = current_user
    if params[:id].to_i == current_user.id
      render :edit
    else
      redirect_to '/404'
    end
  end

  def update
    if !profile_params_blank?
      if current_user.update(profile_params)
        current_user.update(status: true)
        flash[:success] = "Profile succesfully updated!"
        redirect_to profile_path(current_user)
      else
        render :edit
      end
    else
      flash[:notice] = "No changes saved. All fields were blank."
      redirect_to profile_path(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def profile_params
    params.require(:user).permit( :time_zone, :country_code, :interest)
  end

  def profile_params_blank?
    profile_params[:time_zone].blank? && profile_params[:country_code ].blank? && profile_params[:interest].blank?
  end

end

app/views/users/_edit.html.erb
<%= simple_form_for current_user do |f| %>

  <%= f.error_notification %>
  <br><br>

  <p>
    Country:
    <%= f.country_select :country_code %><br>
    <%= f.input :time_zone %>
  </p>

  <%= f.input :interest %>

</div>

  <br><br>

  <div style="text-align: center;">
    <%= f.submit 'Update Profile', class: "btn btn-lg btn-primary" %>
  </div>

  <br><br>

<% end %>

app/views/users/_form.html.erb
<%= simple_form_for @user, url: signup_path, wrapper: :inline_form, html: { class: 'form-inline' } do |f| %>

  <%= f.error_notification input_html: { class: 'error' } %>

  <br><br>

  <%= f.input :name, :placeholder => "Your Username" %>

  <br><br>

  <%= f.input :email, input_html: { autocomplete: 'email' }, :placeholder => "Your Email"  %>

  <br><br>

  <%= f.input :password, input_html: { autocomplete: 'current-password' }, :placeholder => "Your Password"  %>

  <br><br>

  <%= f.submit "Sign Up", class: "btn btn-lg btn-primary" %>

<% end %>

<br><br>

app/views/users/edit.html.erb
<%= render 'users/edit' %>

app/views/users/edit.js.erb
// alert("Hello from Rails!")

//rails processed this first, the javascript sent back was dynamically generated by rails

var html = "<%= j(render('users/edit'))%>"

$("div.edit_profile").html(html)

app/views/users/index.html.erb
<div>
  <div style="text-align: center;">
    <div style="display: inline-block; text-align: left;">

    <h3 align="center">Hi <%= current_user.name.capitalize %>, what are you working on today?</h3>

    <% if current_user.status == false %>
      <h3 align="center">Your account is <%= link_to "pending...", user_path(current_user) %></h4>
    <% end %>

    <li><%= link_to "Your Topics", topics_path(@topics), :class=> "load_topics", :remote => true %></li>

    <div class = "topics">
      <h3>

      </h3>
    </div>

    <li><%= link_to "New Topic", new_topic_path, :class=> "new_topic", :remote => true %></li>
    <div class = "new_topics">
      <h3>

      </h3>
    </div>

    </div>
  </div>
</div>

app/views/users/new.html.erb
<body class="welcome">
  <h1>Sign up </h1>
  <%= render partial: "form", locals: {user: current_user} %>
</body>

app/views/users/show.html.erb
<div>
  <div style="text-align: center;">
    <div style="display: inline-block; text-align: left;">

      <h1>Account Info</h1>

      <% if current_user.status == false %>
        <p><%= link_to "Status: Pending", edit_user_path(current_user), :class=> "edit_profile", :remote => true %></p>

        <p>Your account is <b>pending</b>, fill out profile info. </p>
      <% else %>
        <p>Status: active</p>
        <p><%= link_to "Edit Profile", edit_user_path(current_user), :class=> "edit_profile", :remote => true %></p>
      <% end %>


      <p><strong>Name:</strong> <%= current_user.name %><p>
      <p><strong>Email:</strong> <%= current_user.email %></p><br>

      <p><strong>Time zone:</strong> <%= current_user.time_zone %></p>
      <p><strong>Country:</strong> <%= current_user.country_code %></p>
      <p><strong>Interest:</strong> <%= current_user.interest %></p>


      <div class = "edit_profile">
        <ul>

        </ul>
      </div>



    </div>
  </div>
</div>

app/views/users/show_member.html.erb
<div>
  <div style="text-align: center;">
    <div style="display: inline-block; text-align: left;">

      <h1 align="left">Contact Info</h1>
      <p align="left"><strong>Name:</strong> <%= @member.name%><p>
      <p align="left"><strong>Email:</strong> <%= @member.email%></p>
      <p align="left"><strong>Timezone:</strong> <%= @member.time_zone%></p>
      <p align="left"><strong>Country:</strong> <%= @member.country_code%></p>
      <p align="left"><strong>Interest:</strong> <%= @member.interest%></p><br>

      <div style="width: 400px;margin:auto">
        <img style="width: 400px" src="<%= @member.image %>">
      </div>

  </div>
</div>