config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/404', :to => 'application#not_found'
  get '/422', :to => 'application#unacceptable'
  get '/500', :to => 'application#internal_error'

  get '/auth/google_oauth2/callback', to: 'sessions#create'

  root 'application#welcome', :as => 'welcome'
  # get '/wildcraft_forager' => 'application#enter', :as => 'enter'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/dashboard' => 'users#index', :as => 'main'

  get '/about' => 'application#about', :as => 'about'
  get '/resources' => 'application#reading', :as => 'reading'



  get '/dashboard/categories' => 'categories#index', :as => 'categories'
  get '/categories/:id' => 'categories#show', :as => 'categories_teams'


  delete '/logout' => 'sessions#destroy', :as => 'logout'

  get '/dashboard/profile/:id/edit' => 'users#edit', :as => 'edit_profile'
  get '/dashboard/profile/:id' => 'users#show', :as => 'profile'

  resources :users, path: :profile, shallow: true, only: %i[show edit update]


  get '/members/:id' => 'users#show_member', :as => 'show_member'



  resources :topics do
    resources :posts
  end

  resources :posts do
    resources :comments
  end


  get '/topics/:id/members' => 'users#member_new', :as => 'new_topic_member'
  post '/topics/:id/members/:id' => 'users#member_create'

  get '/members/:id/profile' => 'users#member_show', :as => 'member_profile'


  get '/topics/:id/members' => 'topics#new_member', :as => 'new_member'
  post '/topics/:id/members' => 'topics#create'

end

app/models/post.rb
class Post < ApplicationRecord #formerly topics
  belongs_to :topic, optional: true
  
  has_many :users
  # has_many :comments
  # has_many :users, through: :comments

  include ActiveModel::Validations

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :description,  presence: true

  validates :status, :inclusion => {:in => [true, false]}

  scope :inactive, -> { where(status: true) }
  scope :active, -> { where(status: false) }

  scope :by_recent_update, -> { order(updated_at: :desc) }


  # def self.latest_topic
  #   order('updated_at desc').first
  # end
  #
  # def self.names
  #   pluck(:name)
  # end

  #Project.latest_topic


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in
  before_action :authenticate_user, only: %i[update destroy]

  before_action :set_topic

  def index
    @posts = @topic.posts
    @current_posts = @topic.posts

    if !!@current_posts
      @filters = [["Active", "active"], ["Inactive", "inactive"], ["Recent Update","by_recent_update", {:selected => "selected"}]]

      if params[:sort]
        @current_posts = @current_posts.send(params[:sort][:filters].parameterize.to_sym)
        respond_to do |format|
          format.html {render 'posts/_index.html', :layout => false}
          format.js {render 'index.js', :layout => false}
        end
      else
        @current_posts = @topic.posts.order(updated_at: :desc)
      end

      # # // implicit in rails, explicitly rendering based on format requested
      # respond_to do |format|
      #   format.html {render 'index.html', :layout => false}
      #   format.js {render 'index.js', :layout => false}
      # end

      # render :layout => false
      # render :json => @posts

    end
  end


  # def new
  #   @topic = Topic.find_by_id(params[:topic_id])
  #   @post = Post.new
  # end

  def create
    @topic = Topic.find_by_id(params[:topic_id])
    # @post = Post.new(post_params)

    @post = @topic.posts.build(post_params)
    if @post.save
      respond_to do |f|
        f.html {redirect_to topic_path(@topic)}
        f.json {render :json => @topic}
      end
      # flash[:success] = "Post created successfully!"
      # render 'posts/show', :layout => false
      # @topic.posts << @post
      #
      # flash[:success] = "Post created successfully!"
      # redirect_to @topic
    else
      render "topics/show"
    end
  end


  def show
    @topic = Topic.find_by_id(params[:topic_id])
    @post = Post.find_by_id(params[:id])
    # render json: @post
  end



  def edit
    @post = Post.find_by_id(params[:id])
    @topic = Topic.find_by_id(@post.topic_id)
    unless is_admin?
      redirect_to topic_post_path(@topic, @post)
    end
  end



  def update
    @post = Post.find_by_id(params[:id])
    @topic = Topic.find_by_id(@post.topic_id)
    if @post.update(post_params)
      flash[:update] = "Post updated."
      redirect_to topic_path(@topic)
    else
      render :edit
    end
  end


  def destroy
    @post = Post.find_by_id(params[:id])
    @topic = Topic.find_by_id(@post.topic_id)
    # if @post.topic_id == @topic.id
      @post.delete
    # end
    flash[:notice] = "Post deleted."
    redirect_to @topic
  end


  private

  def set_topic
    @topic = Topic.find_by_id(params[:topic_id])
  end

  def post_params
    params.require(:post).permit(:name, :description, :status)
  end

  def authenticate_user
    if logged_in?
      unless is_admin?
        flash[:error] = "Sorry, admin access only."
      end
    end
  end

  def is_admin?
    @post = Post.find_by_id(params[:id])
    @topic = Topic.find_by_id(@post.topic_id)
    u = Membership.where(user_id: current_user.id, admin: true).distinct.pluck(:user_id)
    u_id = u.join(', ').to_i
    u_id == current_user.id
  end

end

app/views/posts/_form.html.erb
<%= simple_form_for [:topic, @post] do |f| %>

  <%= f.error_notification %>

  <br><br>


  <%= f.input :name, include_blank: false %><br><br>

  <%= f.input :description, include_blank: false %><br><br>

  <br>

  <%= f.submit 'Create', class: "btn btn-lg btn-primary" %>

<% end %>

app/views/posts/_index.html.erb
<%= form_tag(@post, method: :get) do %>
  <%= select(:sort, "filters", options_for_select(@filters)) %>
  <%= submit_tag "Sort" %>
<% end %><br>


<table data-toggle="table">
    <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Created_At</th>
          <th>Updated_At</th>
        </tr>
    </thead>
    <tbody>
      <% count = 0 %>
      <% @current_posts.each do |post, i| %>
        <% count += 1 %>
        <% post_value = i.to_i + count %>
        <tr>
          <td><%= "#{post_value}"%></td>
          <td><%= link_to "#{post.name}", edit_topic_post_path(post.topic_id, post.id) %></td>
          <td><%= post.created_at.strftime("%B %d, %Y, %A") %></td>
          <td><%= post.updated_at.strftime("%B %d, %Y, %A, %k:%M") %></td>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/posts/_new.html.erb
<div>
  <div style="text-align: center;">
    <div style="display: inline-block; text-align: left;">

      <h1 align="center">New Post</h1>
      <h3 align="center">Name: <%= @post.name %></h3>
      <h3 align="center"><%= @failure_message if @failure_message %></h3>
      <h3 align="center"><%= render 'form' %></h3>

      <div style="width: 500px;margin:auto">
        <img style="width: 500px" src="https://images.pexels.com/photos/316465/pexels-photo-316465.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260">
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div>
  <div style="text-align: center;">
    <div style="display: inline-block; text-align: left;">

      <h1 align="center">Edit Post: <%= @post.name %></h1>
      <h3 align="center">Topic: <%= @topic.name %></h3>

      <%= simple_form_for [:topic, @post] do |f| %>

        <%= f.error_notification %>

        <br><br>


        <%= f.input :name, include_blank: false %><br>

        <%= f.input :description, include_blank: false %><br>

        <%= f.label :status, "check box if completed" %>

        <%= f.check_box :status, {}, true, false %>


        <br><br>

        <%= f.submit 'Update', class: "btn btn-lg btn-primary" %>

      <% end %>

      <br><br>

      <%= button_to "Delete Post", { :action => "destroy" }, class: "btn btn-lg btn btn-danger", :method => :delete, data: { confirm: "Are you sure?" } %>

    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'index' %>

app/views/posts/index.js.erb
alert("Hello from Rails!")

//rails processed this first, the javascript sent back was dynamically generated by rails

var html = "<%= j(render('posts/index'))%>"

$("div.posts").html(html)

app/views/posts/new.html.erb
<div>
  <div style="text-align: center;">
    <div style="display: inline-block; text-align: left;">

      <h1 align="center">New Post</h1>
      <h3 align="center">Name: <%= @post.name %></h3>
      <h3 align="center"><%= @failure_message if @failure_message %></h3>
      <h3 align="center"><%= render 'form' %></h3>

      <div style="width: 500px;margin:auto">
        <img style="width: 500px" src="https://images.pexels.com/photos/316465/pexels-photo-316465.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260">
      </div>
    </div>
  </div>
</div>

app/views/posts/new.js.erb
alert("Hello from Rails!")

//rails processed this first, the javascript sent back was dynamically generated by rails

var html = "<%= j(render('posts/new'))%>"

$("div.new_posts").html(html)

app/views/posts/show.html.erb
<div>
  <div style="text-align: center;">
    <div style="display: inline-block; text-align: left;">

      <h1 align="center">Name: <%= @post.name %></h1>
      <h3 align="center">Comment: <%= @post.description %></h3>
      <h3 align="center">Topic: <%= link_to "#{@topic.name}",  edit_topic_path(@topic) %></h3>

    </div>
  </div>
</div>