config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/404', :to => 'application#not_found'
  get '/422', :to => 'application#unacceptable'
  get '/500', :to => 'application#internal_error'

  get '/auth/google_oauth2/callback', to: 'sessions#create'

  root 'application#welcome', :as => 'welcome'
  # get '/wildcraft_forager' => 'application#enter', :as => 'enter'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/dashboard' => 'users#index', :as => 'main'

  get '/about' => 'application#about', :as => 'about'
  get '/resources' => 'application#reading', :as => 'reading'



  get '/dashboard/categories' => 'categories#index', :as => 'categories'
  get '/categories/:id' => 'categories#show', :as => 'categories_teams'


  delete '/logout' => 'sessions#destroy', :as => 'logout'

  get '/dashboard/profile/:id/edit' => 'users#edit', :as => 'edit_profile'
  get '/dashboard/profile/:id' => 'users#show', :as => 'profile'

  resources :users, path: :profile, shallow: true, only: %i[show edit update]


  get '/members/:id' => 'users#show_member', :as => 'show_member'



  resources :topics do
    resources :posts
  end

  resources :posts do
    resources :comments
  end


  get '/topics/:id/members' => 'users#member_new', :as => 'new_topic_member'
  post '/topics/:id/members/:id' => 'users#member_create'

  get '/members/:id/profile' => 'users#member_show', :as => 'member_profile'


  get '/topics/:id/members' => 'topics#new_member', :as => 'new_member'
  post '/topics/:id/members' => 'topics#create'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <small>
      <%= link_to 'WildCraft Forager App', 'https://github.com/JulJen/wildcraft-forager-app', target: :_blank %>

      <copyright>
        &copy;
        <%= link_to 'Julia Jen', 'https://www.linkedin.com/in/juliajen/', target: :_blank %>
        <%= Time.now.year %>
      </copyright>

    </small>


    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Resources", reading_path %></li>
        <li><%= link_to "Contact", reading_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".main-navigation">
        <span class="sr-only">
          Toggle navigation
        </span>
        <span class="icon-bar">
        </span>
        <span class="icon-bar">
        </span>
        <span class="icon-bar">
        </span>
      </button>
      <a class="navbar-brand" href="#">
        WildCraft Forager
      </a>
    </div>
    <div class="collapse navbar-collapse main-navigation">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="#">
            Log Out
          </a>
        </li>
      </ul>
    </div>

    <ul class="nav navbar-nav">
      <li><%= nav_entry "Home", main_path %></li>
      <li><%= nav_entry "Profile", profile_path(current_user) %></li>
      <li><%= nav_entry "Directory", categories_path%></li>
      <li><%= nav_entry "Start a discussion",  new_topic_path %></li>
      <li><%= link_to "Log Out", logout_path, method: :delete %></li>
    </ul>

    <form class="navbar-form navbar-right">
       <div class="form-group">
         <input type="text" class="form-control" placeholder="Search">
       </div>
       <button type="submit" class=", class: 'btn btn-primary navbar-btn'">Submit</button>
     </form>

  </div>
</nav>

app/views/layouts/_login-header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="#">WildCraft Forager</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Sign In', signin_path %></li>
      <li><%= link_to 'Create an Account', signup_path %></li>
      <li><%= link_to 'Log In with Google', '/auth/google_oauth2' %><li>
    </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_testing.html.erb
<div style="width: 400px;margin:auto">
  <img style="width: 400px" src="https://images.pexels.com/photos/1307104/pexels-photo-1307104.jpeg?auto=compress&cs=tinysrgb&h=650&w=940">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildCraft Healer App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Frank+Ruhl+Libre" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

    <link rel="stylesheet" href="bootstrap.min.css">
    <link rel="stylesheet" href="bootstrap-table.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.css">

  </head>



    <%= render 'layouts/shim' %>

    <body>
      <div class= "container">
        <%= flash_messages %>

        <% if current_user %>
          <body class="main">
          <%= render 'layouts/header' %>
        <% elsif current_page?(:controller => 'application', :action => 'welcome') %><br>
          <body class="welcome">
          <%= render 'application/welcome' %>
        <% elsif current_page?(:controller => 'sessions', :action => 'new') || current_page?(:controller => 'users', :action => 'new') %><br>
          <body class="home">
          <%= render 'layouts/login-header' %>
        <% end %>


        <% if !current_page?(:controller => 'application', :action => 'welcome') %>
          <body class="home">
            <div class="center wrapper">
              <div class="center jumbotron-main">
                <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                    <%= yield %>
                  </div>
                </div>
            </div>
          </div>

        <% end %>

        <% if current_user %>
          <%= render '/layouts/footer' %>
        <% end %>
      </div>


    <script src="jquery.min.js"></script>
    <script src="bootstrap.min.js"></script>
    <script src="bootstrap-table.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

  </body>

</html>